import numpy as np
from .cluster import Cluster
from .modules import likelihood_priv as lpriv


class Likelihood:
    """Define a :py:class:`Likelihood` object.

    This object is used to assess how similar your observed cluster is, stored in
    a :py:class:`Cluster <asteca.cluster.Cluster>` object,  compared to a given
    synthetic cluster, generated by the
    :py:meth:`Synthetic.generate() <asteca.synthetic.Synthetic.generate>` method.

    :param my_cluster: :py:class:`Cluster <asteca.cluster.Cluster>` object with the
        loaded data for the observed cluster
    :type my_cluster: Cluster
    :param lkl_name: Currently only the Poisson likelihood ratio (``plr``) defined in
        `Tremmel et al. (2013)
        <https://ui.adsabs.harvard.edu/abs/2013ApJ...766...19T/abstract>`__
        is accepted, defaults to ``plr``
    :type lkl_name: str
    :param bin_method: Bin method used to split the color-magnitude diagram into cells
        (`Hess diagram <https://en.wikipedia.org/wiki/Hess_diagram>`__); one of:
        ``knuth, blocks, scott, freedman or fixed``. See
        `Choosing Histogram Bins <https://docs.astropy.org/en/stable/visualization/histogram.html>`__
        in `astropy <https://www.astropy.org/>`__ documentation for details on the
        ``knuth, blocks, scott, freedman`` methods.  The method ``fixed``
        uses (15, 10) bins in magnitude and color(s) respectively. Defaults to ``knuth``
    :type bin_method: str

    :raises ValueError: If any of the attributes is not recognized as a valid option
    """

    def __init__(
            self,
            my_cluster: Cluster,
            lkl_name: str = "plr",
            bin_method: str = "knuth",
            compute_l: str = "cmd",
            use_kde: bool = False,
            model: str = None,
    ) -> None:
        self.my_cluster = my_cluster
        self.lkl_name = lkl_name
        self.bin_method = bin_method
        self.compute_l = compute_l
        self.use_kde = use_kde
        self.model = model

        likelihoods = ("plr", "bins_distance", "chisq")
        if self.lkl_name not in likelihoods:
            raise ValueError(
                f"'{self.lkl_name}' not recognized. Should be one of {likelihoods}"
            )

        valid_flags = {"cmd", "ccd", "cmd_ccd"}
        if compute_l not in valid_flags:
            raise ValueError(
                f"Invalid value for 'compute_l': '{compute_l}'. Must be one of {valid_flags}."
            )

        bin_methods = ("knuth", "blocks", "scott", "freedman", "fixed")
        if self.bin_method not in bin_methods:
            raise ValueError(
                f"Binning '{self.bin_method}' not recognized. Should be one of {bin_methods}"
            )

        if self.use_kde:
            # Store observed data for KDE likelihood evaluation
            self.obs_data = {
                "obs_mag": my_cluster.mag_v,
                "obs_e_mag": my_cluster.e_mag_v,
                "obs_colors": my_cluster.colors_v,
                "obs_e_colors": my_cluster.e_colors_v,
                # Optionally: "obs_mass": my_cluster.mass_probs if available
            }
        else:
            # Use original histogram-based method
            self.ranges, self.Nbins, self.cl_z_idx, self.cl_histo_f_z = lpriv.lkl_data(
                bin_method, my_cluster.mag_v, my_cluster.colors_v, compute_l
            )

        self.max_lkl = 1.0

        if self.lkl_name == "plr":
            self.max_lkl = 1 - self.get(
                np.array([self.my_cluster.mag_v, *self.my_cluster.colors_v]),
                is_imf_weighted=False
            )

        print("\nLikelihood object generated (use_kde={})".format(self.use_kde))

    def get(self, synth_clust: np.ndarray, is_imf_weighted: bool = False, rmv_contam: bool = False, penalty: bool = True) -> float:
        """Evaluate the selected likelihood function."""
        if self.lkl_name == "plr":
            if self.use_kde:
                # return lpriv.knn_likelihood(self.obs_data, synth_clust, compute_l=self.compute_l, rmv_contam=rmv_contam, model=self.model, penalty=penalty)

                return lpriv.kde_distance(self.obs_data, synth_clust, self.compute_l, rmv_contam=rmv_contam, penalty=penalty)
            else:
                return lpriv.tremmel(
                    self.ranges,
                    self.Nbins,
                    self.cl_z_idx,
                    self.cl_histo_f_z,
                    self.max_lkl,
                    synth_clust,
                    self.compute_l,
                    is_imf_weighted,
                )
        elif self.lkl_name == "bins_distance":
            return lpriv.bins_distance(
                self.my_cluster.mag_v, self.my_cluster.colors_v, synth_clust
            )
        elif self.lkl_name == "chisq":
            return lpriv.chi_square(
                self.ranges, self.Nbins, self.cl_z_idx, self.cl_histo_f_z, synth_clust
            )
        else:
            raise ValueError(f"Likelihood '{self.lkl_name}' not recognized")

